#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done#!/usr/bin/env bash
# comment
while [i -lt 10]
do 
	echo "Best School"
done
