#!/usr/bin/env bash
#comment 23
i=0 
while [ "$i" -lt 10 ]
do
   if [ "$i" -eq 3 ]; then
      echo -e "bad luck\nBest School"
   elif [ "$i" -eq 6 ]; then
      echo -e "good luck\nBest School"
   else 
      echo "Best School"
   fi
   i=$((i+1))
done 
